export default [
    { name: "Gouvernorat de l'Ariana" },
    { name: "Gouvernorat de Béja" },
    { name: "Gouvernorat de Ben Arous" },
    { name: "Gouvernorat de Bizerte" },
    { name: "Gouvernorat de Gabès" },
    { name: "Gouvernorat de Gafsa" },
    { name: "Gouvernorat de Jendouba" },
    { name: "Gouvernorat de Kairouan" },
    { name: "Gouvernorat de Kasserine" },
    { name: "Gouvernorat de Kébili" },
    { name: "Gouvernorat du Kef" },
    { name: "Gouvernorat de Mahdia" },
    { name: "Gouvernorat de Manouba" },
    { name: "Gouvernorat de Médenine" },
    { name: "Gouvernorat de Monastir" },
    { name: "Gouvernorat de Nabeul" },
    { name: "Gouvernorat de Sfax" },
    { name: "Gouvernorat de Sidi Bouzid" },
    { name: "Gouvernorat de Siliana" },
    { name: "Gouvernorat de Sousse" },
    { name: "Gouvernorat de Tataouine" },
    { name: "Gouvernorat de Tozeur" },
    { name: "Gouvernorat de Tunis" },
    { name: "Gouvernorat de Zaghouan" }
  ];;
