export default {
    //Reservation
   
    BUTTONS: {
      btnSuiv: 'BUTTONS.btnSuiv',
      btnPres: 'BUTTONS.btnPres',
      btnConf: 'BUTTONS.btnConf',
      btnAnn: 'BUTTONS.btnAnnule',
      btnRéserver: 'BUTTONS.btnRéserver',
      btnConsulterPanier: 'BUTTONS.btnConsulterPanier',
      btnPaiement: 'BUTTONS.btnPaiement',
      Recharger: 'BUTTONS.Recharger',
      RechargerPortf: 'BUTTONS.RechargerPortf',
      btnLogout: 'BUTTONS.btnLogout',
      btnDelete: 'BUTTONS.btnDelete',
      addToCart: 'BUTTONS.addToCart',
      retirer: 'BUTTONS.retirer',
      Payer: 'BUTTONS.Payer',
      Add: 'BUTTONS.add',
      ContinuePayment: 'BUTTONS.ContinuePayment',
      addToCode: 'BUTTONS.addToCode',
      Confirmer: 'BUTTONS.Confirmer',
      Rechercher: 'BUTTONS.Rechercher',
      addToCreditCard: 'BUTTONS.addToCreditCard',
      Google: 'BUTTONS.Google',
      Facebook: 'BUTTONS.Facebook',
      Apple: 'BUTTONS.Apple',
      ProceedToPayment: 'BUTTONS.ProceedToPayment',
    },
  
  

    message: {
      payment: 'message.payment',
      notFound: 'message.notFound',
    },
    ONBOARDING: {
      titleOne: 'OnBoarding.interface.titleOne',
      titleTwo: 'OnBoarding.interface.titleTwo',
      titleThree: 'OnBoarding.interface.titleThree',
      descOne: 'OnBoarding.interface.descOne',
      descTwo: 'OnBoarding.interface.descTwo',
      descThree: 'OnBoarding.interface.descThree',
      invited: 'OnBoarding.interface.invited',
    },
    Login: {
      SeConnecter: 'login.interface.SeConnecter',
      Sinscrire: 'login.interface.Sinscrire',
      subTitle: 'login.interface.subTitle',
      palcholder: {
        email: 'login.interface.palcholder.email',
        password: 'login.interface.palcholder.password',
        emailForMPO: 'login.interface.palcholder.emailForMPO',
      },
      MDPO: 'login.interface.MDPO',
      Ou: 'login.interface.Ou',
      Google: 'login.interface.Google',
      Facebook: 'login.interface.Facebook',
      EmailRequired: 'login.interface.EmailRequired',
      EmailValid: 'login.interface.EmailValid',
      PasswordRequired: 'login.interface.PasswordRequired',
      ForgetPasswordTitle: 'login.interface.ForgetPasswordTitle',
      ForgetPasswordSubTitle: 'login.interface.ForgetPasswordSubTitle',
      ForgetPasswordTitleSent: 'login.interface.ForgetPasswordTitleSent',
      ForgetPasswordInstruction: 'login.interface.ForgetPasswordInstruction',
    },
    SignUp: {
      textCodeCheckMail: 'signUp.interface.textCodeCheckMail',
      subTextCodeCheckMail: 'signUp.interface.subTextCodeCheckMail',
      titleInformation: 'signUp.interface.titleInformation',
      subTextInfromation: 'signUp.interface.subTextInfromation',
      flelicts: 'signUp.interface.flelicts',
      subTextFelicits: 'signUp.interface.subTextFelicits',
      placeholder: {
        codeCheck: 'signUp.interface.placeholder.codeCheck',
        nom: 'signUp.interface.placeholder.nom',
        prenom: 'signUp.interface.placeholder.prenom',
        tel: 'signUp.interface.placeholder.tel',
        genre: 'signUp.interface.placeholder.genre',
        DtN: 'signUp.interface.placeholder.DtN',
        password: 'signUp.interface.placeholder.password',
      },
      radio: {
        pushMail: 'signUp.interface.radio.pushMail',
        pushMailDescription: 'signUp.interface.radio.pushMailDescription',
        accessData: 'signUp.interface.radio.accessData',
        accessDataDescription: 'signUp.interface.radio.accessDataDescription',
      },
      btns: {
        btnVerifier: 'signUp.interface.btns.btnVerifier',
        btnRenvoyer: 'signUp.interface.btns.btnRenvoyer',
        btnContinuer: 'signUp.interface.btns.btnContinuer',
        btnCommencer: 'signUp.interface.btns.btnCommencer',
      },
      gender: 'signUp.interface.gender',
      EmailRequired: 'signUp.interface.EmailRequired',
      EmailValid: 'signUp.interface.EmailValid',
      PasswordRequired: 'signUp.interface.PasswordRequired',
      FirstNameRequired: 'signUp.interface.FirstNameRequired',
      LastNameRequired: 'signUp.interface.LastNameRequired',
      PhoneNumberRequired: 'signUp.interface.PhoneNumberRequired',
      GenderRequired: 'signUp.interface.GenderRequired',
      DateRequired: 'signUp.interface.DateRequired',
      Caps: 'signUp.interface.Caps',
      FirstNameShort: 'signUp.interface.FirstNameShort',
      LastNameShort: 'signUp.interface.LastNameShort',
      FirstNameLong: 'signUp.interface.FirstNameLong',
      LastNameLong: 'signUp.interface.LastNameLong',
      Short: 'signUp.interface.Short',
      Long: 'signUp.interface.Long',
      FieldRequired: 'signUp.interface.FieldRequired',
      PhoneNumber: 'signUp.interface.PhoneNumber',
      PhoneNumberLength: 'signUp.interface.PhoneNumberLength',
      PasswordSmallLettre: 'signUp.interface.PasswordSmallLettre',
      PasswordCapitalLettre: 'signUp.interface.PasswordCapitalLettre',
      PasswordNumberCheck: 'signUp.interface.PasswordNumberCheck',
      PasswordSpecialCharacter: 'signUp.interface.PasswordSpecialCharacter',
      PasswordMatch: 'signUp.interface.PasswordMatch',
      DateField: 'signUp.interface.DateField',
      signUpErrorTitle: 'signUp.interface.signUpErrorTitle',
      signUpErrorDesc: 'signUp.interface.signUpErrorDesc',
    },  
    
    ROUTES: {
      Intro: 'ROUTES.Intro',
      ONBOARDING: 'ROUTES.ONBOARDING',
    },
  };
  